---
title: "merus length vs carapace width"
author: "Katie Palof"
date: "March 21, 2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
options(scipen=999)
library(xlsx)
library(extrafont)
library(pwr)
loadfonts(device="win")
windowsFonts(Times=windowsFont("TT Times New Roman"))

theme_set(theme_bw(base_size=12,base_family='Times New Roman')+ 
            theme(panel.grid.major = element_blank(),
                  panel.grid.minor = element_blank()))

dat <- read.xlsx("./data/Donaldson Blackburn 1989 Data.xlsx", sheetName = "rinput")
```

## Linear relationship between carapace width and raw merus length


```{r linear, echo = FALSE}
ggplot(dat, aes(width, raw_merus)) + 
         geom_point(size =2) +
         geom_smooth(method =lm)
```

## Confidence and Prediction intervals

```{r intervals, echo=FALSE}
fit1 = lm(raw_merus ~ width, data = dat) 
summary(fit1)
#plot(fit1)

# confidence interval -----
new.dat <- data.frame(width = seq(from =135, to = 215, length.out = 181))
conf_inter <- predict(fit1, newdata = new.dat, interval = 'confidence')
conf_inter <- as.data.frame(conf_inter)

conf_inter %>% 
  bind_cols(new.dat) ->confidenceI

# prediction interval ------
pred_inter <- predict(fit1, newdata = new.dat, interval = 'prediction')
pred_inter <- as.data.frame(pred_inter)

pred_inter %>% 
  bind_cols(new.dat) ->predictionI


# visual of confidence and predictive intervals -----
ggplot(dat, aes(width, raw_merus)) +
        geom_point(size =2, pch = 1) +
        geom_line(data = confidenceI, aes(width, fit), color = "black", size = 1) +
        geom_line(data = confidenceI, aes(width, lwr), color = "red", lty = 2, size = 1) +
        geom_line(data = confidenceI, aes(width, upr), color = "red", lty =2, size = 1) +
        geom_line(data = predictionI, aes(width, lwr), color = "blue", lty = 3, size = 1) +
        geom_line(data = predictionI, aes(width, upr), color = "blue", lty =3, size = 1) +
  xlab("carapace width (mm)") + ylab("merus length (mm)") + ggtitle("carapace width vs raw merus length") +
  geom_vline( xintercept = 177.8)
```


